[JENNIFER]
# Alamat IP Data Server JENNIFER
# Gunakan 127.0.0.1 jika data server di localhost, atau IP Windows Host jika WSL2 terpisah
server_address = 127.0.0.1

# Port Data Server JENNIFER (default: 5000)
server_port = 5000

# ID Domain JENNIFER (sesuai domain di dashboard JENNIFER Anda)
domain_id = 1001

# ID Instance Agen (gunakan -1 agar data server memberikan ID otomatis, atau isi angka unik misal 10019)
inst_id = -1

# Path log agen
log_path = /tmp/jennifer-python-agent.log

# Profiling options
profile_sql = true
profile_sql_param = true
profile_method = true
trace_unhandled_exception = true
